name: app-deploy
on:
  push:
    branches:
      - main
    paths:
      - "app/src/**"
      - "app/vite.config.ts"
      - "app/tsconfig.json"
      - "app/package.json"
      - "app/pnpm-lock.yaml"
      - ".github/workflows/app-deploy.yml"
  workflow_dispatch:
env:
  NO_UPDATE_NOTIFIER: true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AWS-app
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          run_install: false
          package_json_file: ./app/package.json
      - name: Setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 24
          cache: "pnpm"
          cache-dependency-path: "app/pnpm-lock.yaml"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./app
      - name: Audit
        run: pnpm run audit
        working-directory: ./app
      - name: Build
        run: pnpm run build
        env:
          VITE_DATA_URL: ${{ vars.DATA_URL }}
        working-directory: ./app
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
      - name: Add DATA_URL
        run: sed -i "s|__DATA_URL__|${{ vars.DATA_URL }}|g" ./dist/insert-links.js
        working-directory: ./app
      - name: Upload to S3
        run: |
          aws s3 sync dist s3://${{ secrets.APP_BUCKET }} \
            --exclude "index.html" \
            --cache-control "public,max-age=31536000,immutable" \
            --delete
          aws s3 cp dist/index.html s3://${{ secrets.APP_BUCKET }}/index.html \
            --cache-control "no-cache"
        working-directory: ./app
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.APP_DISTRIBUTION }} --paths "/*"
