name: data
on:
  push:
    branches:
      - main
    paths:
      - "data/lambdas/data.py"
      - "data/src/**"
      - "data/pyproject.toml"
      - "data/poetry.lock"
      - "data/Dockerfile"
  pull_request:
    branches:
      - main
    paths:
      - "data/lambdas/data.py"
      - "data/src/**"
      - "data/pyproject.toml"
      - "data/poetry.lock"
      - "data/requirements.txt"
      - "data/Dockerfile"
      - ".github/workflows/data.yml"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  extract-poetry-version:
    permissions:
      contents: read
    uses: ./.github/workflows/poetry-version.yml
  build:
    runs-on: ubuntu-latest
    needs: extract-poetry-version
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Configure AWS Credentials
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
      - name: Login to Amazon ECR
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
      - name: Login to GHCR
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true
      - name: Build image
        run: |
          docker buildx build --provenance=false \
          --build-arg POETRY_VERSION=${{ needs.extract-poetry-version.outputs.poetry-version }} \
          --build-arg BASE_IMAGE=${{ vars.LAMBDA_IMAGE_REPOSITORY}}:${{ vars.LAMBDA_IMAGE_TAG }} \
          -t ${{ vars.DATA_LAMBDA_IMAGE_REPOSITORY }}:${{ vars.DATA_LAMBDA_IMAGE_TAG }} .
        working-directory: ./data
      - name: Push image
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          docker push ${{ vars.DATA_LAMBDA_IMAGE_REPOSITORY }}:${{ vars.DATA_LAMBDA_IMAGE_TAG }}
  deploy:
    runs-on: ubuntu-latest
    environment: AWS-data-lambda
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
      - name: Deploy
        uses: aws-actions/aws-lambda-deploy@29ea35c124579506cf0475e20df36198eb670d89 # v1.1.0
        with:
          function-name: ${{ vars.DATA_LAMBDA_NAME }}
          package-type: Image
          image-uri: "${{ vars.DATA_LAMBDA_IMAGE_REPOSITORY }}:${{ vars.DATA_LAMBDA_IMAGE_TAG }}"
