name: data
on:
  push:
    branches:
      - main
    paths:
      - "data/lambdas/data.py"
      - "data/src/**"
      - "data/pyproject.toml"
      - "data/poetry.lock"
      - "data/Dockerfile"
  pull_request:
    branches:
      - main
    paths:
      - "data/lambdas/data.py"
      - "data/src/**"
      - "data/pyproject.toml"
      - "data/poetry.lock"
      - "data/requirements.txt"
      - "data/Dockerfile"
      - ".github/workflows/data.yml"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  extract-poetry-version:
    permissions:
      contents: read
    uses: ./.github/workflows/poetry-version.yml
  build:
    runs-on: ubuntu-latest
    needs: extract-poetry-version
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Configure AWS Credentials
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
      - name: Login to Amazon ECR
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
      - name: Build image
        run: |
          docker build --build-arg POETRY_VERSION=${{ needs.extract-poetry-version.outputs.poetry-version }} \
          -t ${{ vars.IMAGE_REPOSITORY }}:${{ vars.IMAGE_TAG }} .
        working-directory: ./data
      - name: Push image
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          docker push ${{ vars.IMAGE_REPOSITORY }}:${{ vars.IMAGE_TAG }}
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
      - name: Deploy
        uses: aws-actions/aws-lambda-deploy@29ea35c124579506cf0475e20df36198eb670d89 # v1.1.0
        with:
          function-name: ${{ vars.DATA_LAMBDA_NAME }}
          package-type: Image
          image-uri: "${{ vars.IMAGE_REPOSITORY }}:${{ vars.IMAGE_TAG }}"
