name: poetry-version
on:
  workflow_call:
    outputs:
      poetry-version:
        description: "The extracted Poetry version from requirements.txt"
        value: ${{ jobs.poetry-version.outputs.poetry-version }}
jobs:
  poetry-version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      poetry-version: ${{ steps.poetry-version.outputs.version }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Get Poetry version
        id: poetry-version
        run: |
          VERSION=$(sed -n 's/^poetry==\(.*\)$/\1/p' requirements.txt)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        working-directory: ./data
